spring:
  #应用名称
  application:
    name: springboot-demo
  #数据库相关配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://39.97.253.73:3306/nda?serverTimezone=UTC&amp;characterEncoding=UTF8
    username: root
    password: spm08

server:
  #访问端口号
  port: 8080
  #编码格式
  tomcat:
    uri-encoding: utf-8
